"""create commitments table

Revision ID: f154bdf8a6ad
Revises: 
Create Date: 2026-07-06 03:28:42.112534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f154bdf8a6ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('category', sa.Enum('assignment', 'exam', 'interview', 'meeting', 'project', 'bill', 'health', 'personal', 'event', 'other', name='commitment_category'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'email', 'whatsapp', 'pdf', 'image', 'voice', 'calendar', name='commitment_source'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='commitment_priority'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'missed', 'cancelled', name='commitment_status'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0.0 AND ai_confidence <= 1.0)', name='ck_commitments_ai_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commitments_category', 'commitments', ['category'], unique=False)
    op.create_index('ix_commitments_deadline', 'commitments', ['deadline'], unique=False)
    op.create_index('ix_commitments_priority', 'commitments', ['priority'], unique=False)
    op.create_index('ix_commitments_status', 'commitments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commitments_status', table_name='commitments')
    op.drop_index('ix_commitments_priority', table_name='commitments')
    op.drop_index('ix_commitments_deadline', table_name='commitments')
    op.drop_index('ix_commitments_category', table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###
